-- 접속한 계정의 테이블 목록 조회
SELECT TABLE_NAME
  FROM USER_TABLES;
 
-- 접속한 계정의 테이블별 컬럼 조회
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_PRECISION, DATA_LENGTH, NULLABLE, DATA_DEFAULT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME IN ('EMPLOYEE', 'DEPARTMENT', 'TITLE');

-- 접속한 계정의 테이블별 제약조건 조회
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION, DELETE_RULE
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME IN ('EMPLOYEE', 'DEPARTMENT', 'TITLE');
 

SELECT * FROM TITLE;
SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;

SELECT TITLE_NO , TITLE_NAME FROM TITLE;

INSERT INTO TITLE VALUES (6, '인턴');
SELECT TITLE_NO, TITLE_NAME FROM TITLE;

DELETE FROM TITLE t WHERE TITLE_NO = 6;

UPDATE TITLE SET TITLE_NAME = '계약직' WHERE TITLE_NO = 6;
DELETE FROM TITLE t WHERE TITLE_NO = 6;

SELECT *
  FROM EMPLOYEE e JOIN TITLE t ON E.TNO = T.TITLE_NO 
       JOIN DEPARTMENT d ON E.DNO = D.DEPT_NO ;